apiVersion: v1
data:
  app-major-version: '1'
  app-minor-version: '2'
  app-name: hello-kubernetes-canary
  config-version: '1'
  deploy-dev: 'true'
  deploy-preprod: 'false'
  deploy-prod: 'false'
  github-org: airwalk-mj
  source-branch: main
  source-repo: 'https://github.com/airwalk-mj/hello-kubernetes/canary'
  target-image: 'markdavidjames/hello-kubernetes'
kind: ConfigMap
metadata:
  name: app-config
